name: Nicko
main: net.artelnatif.nicko.bukkit.NickoBukkit
version: 1.0-SNAPSHOT
author: Aro
api-version: 1.19
softdepend: [ PlaceholderAPI ]
commands:
  nicko:
    description: "Opens Nicko's GUI."
    permission: nicko.admin
permissions:
  nicko.*:
    default: op
    children:
      - nicko.use
  nicko.use:
    default: op