# Nicko's docker-compose.yml
# Used for debug and test purposes.
version: '3.1'

services:

  db:
    image: mariadb:latest
    restart: no
    environment:
      MARIADB_DB: db
      MARIADB_ROOT_PASSWORD: 12345
    volumes:
        - mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis
    restart: no
    ports:
      - "6379:6379"

volumes:
  mysql: