# Nicko's docker-compose.yml
# Used for debug and test purposes.
version: '3.1'

services:

  db:
    image: mariadb
    restart: no
    environment:
      MARIADB_ROOT_PASSWORD: 12345
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    restart: no
    links:
      - db
    ports:
      - "8080:80"

  redis:
    image: redis
    restart: no
    ports:
      - "6379:6379"
