name: Nicko
main: xyz.ineanto.nicko.Nicko
loader: xyz.ineanto.nicko.loader.NickoPluginLoader
version: ${version}
author: Ineanto
description: "The feature packed, next generation disguise plugin for Minecraft."
api-version: "1.21"
softdepend: [ PlaceholderAPI ]
depend:
  - ProtocolLib

dependencies:
  server:
    ProtocolLib:
      load: BEFORE
      join-classpath: true

permissions:
  nicko.*:
    default: op
    children:
      - nicko.use
  nicko.use:
    default: false