name: Nicko
main: xyz.ineanto.nicko.Nicko
loader: xyz.ineanto.nicko.loader.NickoLibraryLoader
version: ${version}
authors: [ Ineanto ]
description: "The feature packed, next generation disguise plugin for Minecraft."
api-version: "1.20"
dependencies:
  server:
    { "ProtocolLib" }
permissions:
  nicko.*:
    default: op
    children:
      - nicko.use
  nicko.use:
    default: false