name: Nicko
main: xyz.ineanto.nicko.Nicko
loader: xyz.ineanto.nicko.loader.NickoPluginLoader
version: ${version}
author: Ineanto
description: "The feature packed, next generation disguise plugin for Minecraft."
api-version: "1.21"
softdepend: [ PlaceholderAPI ]
depend:
  - ProtocolLib

# Suppose we require ProtocolLib to be loaded for our plugin
AnvilGUI:
  join-classpath: true
  required: true

permissions:
  nicko.*:
    default: op
    children:
      - nicko.use
  nicko.use:
    default: false