name: Nicko
main: xyz.atnrch.nicko.NickoBukkit
version: 1.0-SNAPSHOT
author: Ineanto
description: "In-game appearance manager."
api-version: 1.13
softdepend: [ PlaceholderAPI ]
depend:
  - ProtocolLib
load: POSTWORLD
commands:
  nicko:
    description: "Opens Nicko's GUI."
    permission: nicko.use
permissions:
  nicko.*:
    default: op
    children:
      - nicko.use
  nicko.use:
    default: false